# Generated by Django 4.1.3 on 2022-11-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Astrologer', 'Astrologer'), ('Normal user', 'Normal_user')], default='Normal user', max_length=30),
        ),
    ]
