# Generated by Django 4.1.3 on 2022-12-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(default='Say something about yourself', max_length=1000),
        ),
    ]
