# Generated by Django 4.1.3 on 2022-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F'), ('OTHERS', 'O')], default='OTHERS', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Astrologer', 'Astrologer'), ('Normal_User', 'Normal user')], default='Normal_User', max_length=30),
        ),
    ]
