# Generated by Django 4.1.3 on 2023-01-02 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='astrologer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astrologer_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointment', to=settings.AUTH_USER_MODEL),
        ),
    ]
