# Generated by Django 4.1.3 on 2022-12-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_accountverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountVerification',
        ),
    ]
